name = "Harvista"
author = "Nixieboluo, HaooooZhang"
version = "3.1.2-ourmoe+r2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a5d432b71e8069f2edba8ec5e3e957421cb223f92efe15445b9faf081ad857a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
