name: build-modpack

on:
    push:
        tags:
            - '*'

jobs:
    build-pack:
        name: Use packwiz to build the modrinth pack
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup Go environment
              uses: actions/setup-go@v5.0.0
              with:
                  go-version: '>=1.19.0'

            - name: Install Packwiz
              run: |
                  go install github.com/packwiz/packwiz@latest

            - name: Build pack
              run: packwiz modrinth export

            - name: Upload pack to actions
              uses: actions/upload-artifact@v4
              with:
                  path: Harvista-*.zip
